class EventTypes {
    static ENC_NODE_SELECTED = "ENC_NODE_SELECTED";
    static ENC_NODE_MOUSE_ENTER = "ENC_NODE_MOUSE_ENTER";
    static ENC_NODE_MOUSE_LEAVE = "ENC_NODE_MOUSE_LEAVE";
    static INFO_NODE_SELECTED = "INFO_NODE_SELECTED";
    static INFO_NODE_MOUSE_ENTER = "INFO_NODE_MOUSE_ENTER";
    static INFO_NODE_MOUSE_ENTER = "INFO_NODE_MOUSE_LEAVE";
}